apps/crud/models.py
from datetime import datetime
from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model , UserMixin):
    __tablename__="weather"
    id= db.Column(db.Integer, primary_key=True)
    days=db.Column(db.Date, index=True)
    amWeather= db.Column(db.String, index=True)
    pmWeather= db.Column(db.String, index=True)
    temmin= db.Column(db.Integer, index=True)
    temmax= db.Column(db.Integer, index=True)
    
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")
    
    @password.setter
    def password(self, password):
        self.password_hash=generate_password_hash(password)


    def verify_password(self, password):
        return check_password_hash(self.password_hash,password)
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)
    


class Acount(db.Model , UserMixin):
    __tablename__="acount"
    id= db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String, index=True)
    email= db.Column(db.String,unique=True, index=True)
    password_hash=db.Column(db.String)
    created_at=db.Column(db.DateTime, default=datetime.now)
    updated_at= db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now
    )

    # 속성값 getter
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")
    
    @password.setter
    def password(self, password):
        self.password_hash=generate_password_hash(password)


    def verify_password(self, password):
        return check_password_hash(self.password_hash,password)
    def is_duplicate_email(self):
        return Acount.query.filter_by(email=self.email).first() is not None
    
    @login_manager.user_loader
    def load_user(user_id):
        return Acount.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,DateField,IntegerField
from wtforms.validators import DataRequired
#wtforms.validators:유효성 검증 관련 모듈
#DataRequired:이 필드는 반드시 값을 써야 하는 필드
#Email:이메일 형식을 반드시 지켜야 하는 필드
#length:입력한 값의 길이 관련
class UserForm(FlaskForm):
    days=DateField(
        "날짜",
        validators=[
            DataRequired(message="날짜 입력은 필수입니다."),
        ],
    )
    amWeather=StringField(
        "오전 날씨",
        validators=[
            DataRequired(message="오전 날씨는 필수입니다."),
        ],
    )
    pmWeather=StringField(
        "오후 날씨",
        validators=[
            DataRequired(message="오후 날씨는 필수입니다."),
        ],
    )
    temmin=IntegerField(
        "최저 기온",
        validators=[
            DataRequired(message="최저 기온은 필수입니다."),
        ],
    )
    temmax=IntegerField(
        "최고 기온",
        validators=[
            DataRequired(message="최고 기온은 필수입니다."),
        ],
    )
    submit = SubmitField("신규 등록")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, render_template,redirect, url_for, request
from apps.crud.forms import UserForm
from apps.app import db
from apps.crud.models import User
from flask_login import login_required

crud= Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static"
)

@crud.route("/")
def index():
    return render_template("crud/index.html")

@crud.route("/new", methods=["GET","POST"])
@login_required
def create_user():
    form=UserForm()
    if form.validate_on_submit():
        user=User(
            days=form.days.data,
            amWeather=form.amWeather.data,
            pmWeather=form.pmWeather.data,
            temmin=form.temmin.data,
            temmax=form.temmax.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)

@crud.route("/inf")
@login_required
def users():
    users=User.query.all()
    return render_template("crud/inf.html",users=users)

@crud.route("/inf/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user=User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

@crud.route("/inf/<user_id>", methods=["GET"]) 
def users_result(user_id):
    print(user_id)
    user_src = None
    users=User.query.filter_by(id=user_id).first()
    if not users :
        return "데이터가 없어요"
    if users.amWeather=="맑음":
        user_src1="맑음.png"
    if users.amWeather=="구름":
        user_src1="구름.png"
    if users.amWeather=="비":
        user_src1="비.png"
    if users.pmWeather=="맑음":
        user_src2="맑음.png"
    if users.pmWeather=="비":
        user_src2="비.png"
    if users.pmWeather=="구름":
        user_src2="구름.png"       
    return render_template("crud/result.html",user=users, user_src1=user_src1, user_src2=user_src2)


@crud.route("/inf/<user_id>/edit", methods=["POST","GET"])
@login_required
def edit_user(user_id):
    form=UserForm()
    user=User.query.filter_by(id=user_id).first()
    if request.method == "POST" :
        user.days = form.days.data
        user.amWeather = form.amWeather.data
        user.pmWeather = form.pmWeather.data
        user.temmin = form.temmin.data
        user.temmax = form.temmax.data
        
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))
    
    return render_template("crud/edit.html", user=user, form=form)

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('crud.static',filename='style.css')}}"/>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}CRUD{% endblock %}
{% block content %}<h2>사용자 신규 작성</h2>
<form action="{{url_for('crud.create_user')}}" method="POST" novalidate="novalidate">
    <div class="bg-video">
        <video class="bg-video__content" autoplay muted loop>
            <source src="{{url_for('crud.static',filename='날씨.mp4')}}" type="video/mp4" />
        </video>
    </div>
    {{form.csrf_token}}
    <p>
        {{form.days.label}}{{form.days(placeholer="날짜")}}
    </p>
    
    {% for error in form.days.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor%}
    
    <p>
        {{form.amWeather.label}}{{form.amWeather(placeholer="오전 날씨")}}
    </p>
    {% for error in form.amWeather.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    <p>
        {{form.pmWeather.label}}{{form.pmWeather(placeholer="오후 날씨")}}
    </p>
    {% for error in form.pmWeather.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    <p>
        {{form.temmin.label}}{{form.temmin(placeholer="최저 기온")}}
    </p>
    {% for error in form.temmin.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    <p>
        {{form.temmax.label}}{{form.temmax(placeholer="최고 기온")}}
    </p>
    {% for error in form.temmax.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    
    
    <p>{{form.submit()}}</p>
    </form>
    <button ><a href="{{url_for('crud.users')}}" class="뒤로">뒤로</a></button>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}사용자 편집{% endblock %}
{% block content %}
    <h2>사용자 편집</h2>
    <form
    action="{{url_for('crud.edit_user',user_id=user.id)}}"
    method="POST"
    novalidate="novalidate"
    >
 
    <p>
        {{form.days.label}}{{form.days(placeholer="날짜")}}
    </p>
    
    {% for error in form.days.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor%}
    
    <p>
        {{form.amWeather.label}}{{form.amWeather(placeholer="오전 날씨")}}
    </p>
    {% for error in form.amWeather.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    <p>
        {{form.pmWeather.label}}{{form.pmWeather(placeholer="오후 날씨")}}
    </p>
    {% for error in form.pmWeather.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    <p>
        {{form.temmin.label}}{{form.temmin(placeholer="최저 기온")}}
    </p>
    {% for error in form.temmin.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    <p>
        {{form.temmax.label}}{{form.temmax(placeholer="최고 기온")}}
    </p>
    {% for error in form.temmax.errors %}
    <span style="color: red;">{{error}}</span>
    {% endfor %}
    
    <p><input type="submit" value="갱신"/></p>
    </form>
    
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}CRUD{% endblock %}
{% block content %} 
<div class="bg-video">
    <video class="bg-video__content" autoplay muted loop>
        <source src="{{url_for('crud.static',filename='날씨.mp4')}}" type="video/mp4" />
    </video>
  </div>
<h1>주간 날씨예보</h1>
<div class="week">
    
    <div class="container">
    <img src="{{url_for('crud.static',filename='월요일.png')}}" type="png">
    <a href="{{url_for('crud.users_result', user_id=1)}}" >Mon</a>
    </div>
    
    <div class="container">
    <img src="{{url_for('crud.static',filename='화요일.png')}}" type="png">
    <a href="{{url_for('crud.users_result', user_id=2)}}" >Tue</a>
    </div>
    
    <div class="container">
    <img src="{{url_for('crud.static',filename='수요일.png')}}" type="png">
    <a href="{{url_for('crud.users_result', user_id=3)}}" >Wed</a>
    </div>
   
    <div class="container">
    <img src="{{url_for('crud.static',filename='목요일.png')}}" type="png">
    <a href="{{url_for('crud.users_result', user_id=4)}}" >Thu</a>
    </div>
    

    <div class="container">
    <img src="{{url_for('crud.static',filename='금요일.png')}}" type="png">
    <a href="{{url_for('crud.users_result', user_id=5)}}" >Fri</a>
    </div>
    

    <div class="container">
    <img src="{{url_for('crud.static',filename='토요일.png')}}" type="png">
    <a href="{{url_for('crud.users_result', user_id=6)}}" >Sat</a>
    </div>
    
    <div class="container">
    <img src="{{url_for('crud.static',filename='일요일.png')}}" type="png">      
    <a href="{{url_for('crud.users_result', user_id=7)}}" >Sun</a>
    </div>
</div>
{% if not current_user.is_authenticated %}
<button class="로그인"><a href="{{url_for('auth.login')}}" class="뒤로">로그인</a></button>
{% endif %}
{% endblock %}

apps/crud/templates/crud/inf.html
{% extends "crud/base.html" %}
{% block title %}CRUD{% endblock %}
{% block content %} <h2>날씨 데이터 작성</h2>
<div class="bg-video">
    <video class="bg-video__content" autoplay muted loop>
        <source src="{{url_for('crud.static',filename='날씨.mp4')}}" type="video/mp4" />
    </video>
</div>
<a href="{{url_for('crud.create_user')}}">날씨 신규 작성</a>

<table>
    <tr>
        <th>사용자 ID</th>
        <th>day</th>
        <th>오전 날씨</th>
        <th>오후 날씨</th>
        <th>최저 기온</th>
        <th>최고 기온</th>
        <th>삭제</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            <a href="{{url_for('crud.edit_user',user_id=user.id)}}">{{user.id}}</a>
        </td>
        <td>{{user.days}}</td>
        <td>{{user.amWeather}}</td>
        <td>{{user.pmWeather}}</td>
        <td>{{user.temmin}}</td>
        <td>{{user.temmax}}</td>
        <td>
        <form action="{{url_for('crud.delete_user',user_id=user.id)}}" method="POST" >
           
            <input type="submit" value="삭제">
        </form>
        </td>
    </tr>
    {% endfor %}
</table>
<button ><a href="{{url_for('crud.index')}}" class="뒤로">뒤로</a></button>
{% endblock %}

apps/crud/templates/crud/result.html
{% extends "crud/base.html" %}
{% block title %}CRUD{% endblock %}
{% block content %} 
<div class="bg-video">
    <video class="bg-video__content" autoplay muted loop>
      <source src="{{url_for('crud.static',filename='날씨.mp4')}}" type="video/mp4" />
    </video>
</div>
<h1>상세 날씨</h1>
<!-- <table>
    <tr>
        <th>day</th>
        <th>오전 날씨</th>
        <th>오후 날씨</th>
        <th>최저 기온</th>
        <th>최고 기온</th>

    </tr>
    <tr>
        <td>{{user.days}}</td>
        <td>{{user.amWeather}}</td>
        <td>{{user.pmWeather}}</td>
        <td>{{user.temmin}}</td>
        <td>{{user.temmax}}</td>
    </tr>
</table> -->

<div class="result">
<div class="icons">

<img src="{{ url_for('crud.static', filename=user_src1) }}"  type="png" class="icon">

<img src="{{ url_for('crud.static', filename=user_src2) }}"  type="png" class="icon">



</div>


<ul>
    <li>{{user.days}}</li>
    <li>오전 날씨 {{user.amWeather}}</li>
    <li>오후 날씨 {{user.pmWeather}}</li>
    <li>최저 기온 {{user.temmin}}</li>
    <li>최고 기온 {{user.temmax}}</li>
</ul>

<div class="buttonContainer">
    <button class="로그인"><a href="{{url_for('crud.users')}}" class="뒤로">수정</a></button>
<button><a href="{{url_for('crud.index')}}" class="뒤로">뒤로</a></button>
</div>
</div>

<!-- <script>
    if (user.amWeather=="맑음"){
        return user_src="{{url_for('crud.static',filename='맑음.png')}}" 
    }
</script> -->
{% endblock %}